<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "slub_find_extend"
 *
 * Auto generated by Extension Builder 2015-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'Find configuration for SLUB Catalog',
    'description' => '',
    'category' => 'plugin',
    'author' => 'Christof Rodejohann',
    'author_email' => 'typo3@slub-dresden.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.21',
    'constraints' => array(
        'depends' => array(
            'typo3' => '9.5.0-9.5.99'
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
